// `softure-blog skill install`: the writing skill of `skill/`, rendered with the app's blog config.
// The templates hold `{{name}}` values and `{{#flag}}…{{/flag}}` / `{{^flag}}…{{/flag}}` sections;
// `references/rules.md` holds one table row per built-in rule, which gets the effective severity
// and the catalog's description, or is dropped when the app's gate does not enforce the rule.
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import type { SoftureConfig } from "@softure-ai/core";
import { listQualityRules, type QualityCatalogRule } from "../quality/catalog.js";
import type { QualitySettings } from "../quality/settings.js";
import { getBlogOptions, getBlogReservedSlugs, getQualitySettings } from "../server/options.js";

/** The folder the skill installs into, relative to the app's root. */
export const DEFAULT_SKILL_DIR = ".claude/skills/blog-write";
/** How the skill tells the agent to run the command. */
export const DEFAULT_SKILL_COMMAND = "npx softure-blog";
/** The line every generated `SKILL.md` holds; install overwrites only a folder whose `SKILL.md` has it. */
export const SKILL_MARKER = "<!-- Generated by `softure-blog skill install`";

/** `modules/blog/skill/`, from `src/cli/` and from `dist/cli/` alike. */
const TEMPLATE_DIR = fileURLToPath(new URL("../../skill/", import.meta.url));
const RULES_TEMPLATE = "references/rules.md";

export type SkillValues = Readonly<Record<string, string | boolean>>;

export interface SkillFile {
  /** Relative to the skill folder, with `/`. */
  readonly path: string;
  readonly text: string;
}

export interface RenderBlogSkillOptions {
  /** How the skill names the command. Default: `npx softure-blog`. */
  readonly command?: string;
}

const LANGUAGE_NAMES: Readonly<Record<string, string>> = { en: "English", pl: "Polish" };

/** The skill's files for the app's config. Throws when the gate is off: the skill is built on it. */
export function renderBlogSkill(config: SoftureConfig, options: RenderBlogSkillOptions = {}): SkillFile[] {
  const settings = getQualitySettings(config);
  if (settings === null) throw new Error("the quality gate is off (blog({ quality: false })); the writing skill is built on it");
  const values = getSkillValues(config, settings, options);
  const rules = listQualityRules(settings);
  return listTemplateFiles().map((path) => {
    const rendered = renderSkillTemplate(readFileSync(join(TEMPLATE_DIR, path), "utf8"), values);
    return { path, text: path === RULES_TEMPLATE ? fillRulesTables(rendered, rules) : rendered };
  });
}

/** The values the templates read. */
export function getSkillValues(config: SoftureConfig, settings: QualitySettings, options: RenderBlogSkillOptions = {}): SkillValues {
  const blogOptions = getBlogOptions(config);
  const { limits, ymyl, voice, paths, plugins } = settings.options;
  const fieldKeys = Object.keys(blogOptions.fields?.shape ?? {});
  const reservedSlugs = getBlogReservedSlugs(config);
  return {
    command: options.command ?? DEFAULT_SKILL_COMMAND,
    language: settings.ruleset.language,
    languageName: LANGUAGE_NAMES[settings.ruleset.language] ?? settings.ruleset.language,
    contentDir: trimTrailingSlashes(blogOptions.contentDir),
    articlesPath: paths.articles,
    termsPath: paths.terms,
    articleWordsMin: String(limits.words.article.min),
    articleWordsMax: String(limits.words.article.max),
    termWordsMin: String(limits.words.term.min),
    termWordsMax: String(limits.words.term.max),
    leadWordsArticle: String(limits.leadWords.article),
    leadWordsTerm: String(limits.leadWords.term),
    answerWords: String(limits.answerWords),
    internalLinksArticle: String(limits.internalLinks.article),
    internalLinksTerm: String(limits.internalLinks.term),
    staleAfterDays: String(limits.staleAfterDays),
    titleChars: String(limits.titleChars),
    descriptionCharsMin: String(limits.descriptionChars.min),
    descriptionCharsMax: String(limits.descriptionChars.max),
    wordsPerDash: String(limits.wordsPerDash),
    wordsPerBold: String(limits.wordsPerBold),
    sentenceWords: String(limits.sentenceWords),
    ymyl: ymyl !== null,
    ownCalculationMark: ymyl?.ownCalculationMark ?? false,
    firstPersonSingular: voice.forbidFirstPersonSingular,
    plugins: plugins.length > 0,
    fields: fieldKeys.length > 0,
    fieldKeys: fieldKeys.map((key) => `\`${key}\``).join(", "),
    reservedSlugs: reservedSlugs.length > 0,
    reservedSlugList: reservedSlugs.map((slug) => `\`${slug}\``).join(", "),
    appRules: "",
  };
}

/** Without trailing slashes; a loop, not a regular expression, so a long run of slashes stays linear. */
function trimTrailingSlashes(path: string): string {
  let end = path.length;
  while (end > 1 && path[end - 1] === "/") end -= 1;
  return path.slice(0, end);
}

const STANDALONE_SECTION_TAG = /^[ \t]*(\{\{[#^/][A-Za-z]+\}\})[ \t]*\r?\n/gm;
const TAG = /\{\{([#^/]?)([A-Za-z]+)\}\}/g;

/**
 * Fills `{{name}}` with a value and keeps `{{#flag}}…{{/flag}}` when the value is truthy (a non-empty
 * string or `true`), `{{^flag}}…{{/flag}}` when it is not. A tag alone on its line takes the line with
 * it. Throws on a name without a value and on a section that does not close, naming it.
 */
export function renderSkillTemplate(template: string, values: SkillValues): string {
  const source = template.replace(STANDALONE_SECTION_TAG, "$1");
  const getValue = (name: string): string | boolean => {
    const value = values[name];
    if (value === undefined) throw new Error(`skill template: no value for {{${name}}}`);
    return value;
  };

  const stack: { name: string; inverted: boolean; keep: boolean }[] = [];
  let output = "";
  let last = 0;
  const isKept = () => stack.every((section) => section.keep);
  for (const match of source.matchAll(TAG)) {
    const [tag, kind = "", name = ""] = match;
    if (isKept()) output += source.slice(last, match.index);
    last = match.index + tag.length;
    if (kind === "#" || kind === "^") {
      const truthy = isTruthy(getValue(name));
      stack.push({ name, inverted: kind === "^", keep: kind === "^" ? !truthy : truthy });
    } else if (kind === "/") {
      const open = stack.pop();
      if (open?.name !== name) throw new Error(`skill template: {{/${name}}} closes ${open === undefined ? "nothing" : `{{${open.inverted ? "^" : "#"}${open.name}}}`}`);
    } else if (isKept()) {
      const value = getValue(name);
      if (typeof value !== "string") throw new Error(`skill template: {{${name}}} is a flag; use it as a section`);
      output += value;
    }
  }
  const unclosed = stack.at(-1);
  if (unclosed !== undefined) throw new Error(`skill template: {{${unclosed.inverted ? "^" : "#"}${unclosed.name}}} is not closed`);
  return output + source.slice(last);
}

function isTruthy(value: string | boolean): boolean {
  return typeof value === "string" ? value.length > 0 : value;
}

/** A row of a rules table in the template: `` | `rule-id` | | | guidance | ``. */
const TEMPLATE_RULE_ROW = /^\| `([a-z0-9-]+)` \| \| \| (.*) \|$/;
const RULES_TABLE_HEADER = "| Rule | Severity | What the gate looks for | What to write instead |";
const APP_RULES_SLOT = "## The app's own rules\n\n";

/** The rule ids the template's tables name. */
export function findTemplateRuleIds(rulesTemplate: string): string[] {
  return rulesTemplate.split("\n").flatMap((line) => {
    const match = TEMPLATE_RULE_ROW.exec(line);
    return match?.[1] === undefined ? [] : [match[1]];
  });
}

/**
 * Fills the rows of rules the gate enforces with their severity and description, drops the rows of
 * rules it does not, drops a table (and its heading) left without rows, and lists every catalog rule
 * the template has no row for (the app's voice phrases and plugin rules) under the app's own rules.
 */
export function fillRulesTables(text: string, rules: readonly QualityCatalogRule[]): string {
  const byId = new Map(rules.map((rule) => [rule.id, rule]));
  const filled = text.split("\n").flatMap((line) => {
    const match = TEMPLATE_RULE_ROW.exec(line);
    if (match === null) return [line];
    const [, id = "", guidance = ""] = match;
    const rule = byId.get(id);
    return rule === undefined ? [] : [`| \`${id}\` | ${formatSeverity(rule)} | ${escapeCell(rule.description)} | ${guidance} |`];
  });
  const named = new Set(findTemplateRuleIds(text));
  const appRules = rules.filter((rule) => !named.has(rule.id));
  const appTable =
    appRules.length === 0
      ? "None: the gate enforces only the rules above."
      : [
          "Rules of the app's voice and its plugins; the description is the app's own.",
          "",
          "| Rule | Severity | What the gate looks for |",
          "| --- | --- | --- |",
          ...appRules.map((rule) => `| \`${rule.id}\` | ${formatSeverity(rule)} | ${escapeCell(rule.description)} |`),
        ].join("\n");
  return dropEmptyTables(filled.join("\n")).replace(APP_RULES_SLOT, `${APP_RULES_SLOT}${appTable}`);
}

function formatSeverity(rule: QualityCatalogRule): string {
  return rule.severity === "error" ? "**error**" : "warning";
}

function escapeCell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll("\n", " ");
}

/** Removes a `## ` section whose rules table has no rows left. */
function dropEmptyTables(text: string): string {
  return text
    .split(/\n(?=## )/)
    .filter((section) => {
      if (!section.includes(RULES_TABLE_HEADER)) return true;
      return section.split("\n").some((line) => line.startsWith("| `"));
    })
    .join("\n");
}

/** The template files, relative to `skill/`. */
export function listTemplateFiles(): string[] {
  const files: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith(".md")) files.push(relative(TEMPLATE_DIR, path).split("\\").join("/"));
    }
  };
  walk(TEMPLATE_DIR);
  return files.sort();
}

/** The text of one template file, as shipped. */
export function readSkillTemplate(path: string): string {
  return readFileSync(join(TEMPLATE_DIR, path), "utf8");
}
