import type { Scene } from "@softure-ai/marketing-kit";

/**
 * The fixture film's scene over the fixture app (`../app/index.html`); its script (sentences, opening,
 * screen guard, end card) is the `fixture-tour` entry of `../marketing.json`. It types an age, taps
 * "Next", checks that the screen shows what the voiceover says and ends on the end card. Its
 * voiceover is generated by `../prepare.ts` (a tone with evenly spaced word timings), never paid for.
 */
export const scene: Scene = async (d) => {
  const { page } = d;

  await d.beat("age", async () => {
    await d.fill("age", "36");
    await d.until("taps");
    await d.cue("sparkle");
    await d.tap(page.getByRole("button", { name: /^Next$/ }), { after: 0.3 });
    await d.cue("persona-out");
    await d.wide({ whoosh: true });
    await d.mark("exit-age", page.locator("#exit-age"));
    await d.mark("exit-date", page.locator("#exit-date"));
    await d.focus([page.locator("#exit-age"), page.locator("#exit-date")], { scale: 1.3 });
    await d.checkScreen();
    await d.hold(0.6);
    await d.still("result");
  });

  await d.beat(
    "cta",
    async () => {
      await d.wide();
      await d.bring(page.getByRole("heading"), { top: 40, seconds: 0.4 });
    },
    { pad: 1.2 },
  );
};
