import type { Film } from "@softure-ai/marketing-kit";

/**
 * The fixture film: three sentences over the fixture app (`../app/index.html`). It types an age,
 * taps "Next", checks that the screen shows what the voiceover says and ends on the end card. Its
 * voiceover is generated by `../prepare.ts` (a tone with evenly spaced word timings), never paid for.
 */
export const film: Film = {
  id: "fixture-tour",
  title: "The fixture counts its date",
  persona: { name: "Robin", age: 36, tagline: "works out when to stop working" },
  voice: { voiceId: "fixture-voice", modelId: "fixture-model", tempo: 1.1 },
  beats: [
    { id: "hook", text: "Forty-nine years. That is the exit age." },
    { id: "age", text: "Robin types thirty-six and taps next." },
    { id: "cta", text: "Count your own date today." },
  ],
  hook: {
    still: "result",
    shots: [
      { mark: "exit-age", scale: 1.6 },
      { mark: "exit-date", scale: 1.3, word: "That" },
    ],
  },
  screenGuard: ["49 years", "March 2040"],
  channels: { instagram: "ig-01", facebook: "fb-01", tiktok: "tiktok-01" },
  endCard: { headline: "Count your date", url: "example.com/calculator", note: "Free, no account" },
  post: { caption: "Robin is 36 and can stop working at 49.", hashtags: ["fire", "#money"] },

  async scene(d) {
    const { page } = d;

    await d.beat("age", async () => {
      await d.fill("age", "36");
      await d.until("taps");
      await d.cue("sparkle");
      await d.tap(page.getByRole("button", { name: /^Next$/ }), { after: 0.3 });
      await d.cue("persona-out");
      await d.wide({ whoosh: true });
      await d.mark("exit-age", page.locator("#exit-age"));
      await d.mark("exit-date", page.locator("#exit-date"));
      await d.focus([page.locator("#exit-age"), page.locator("#exit-date")], { scale: 1.3 });
      await d.checkScreen();
      await d.hold(0.6);
      await d.still("result");
    });

    await d.beat(
      "cta",
      async () => {
        await d.wide();
        await d.bring(page.getByRole("heading"), { top: 40, seconds: 0.4 });
      },
      { pad: 1.2 },
    );
  },
};
