# Helpers for softure-example's deploy hooks, generated by `softure-deploy init` (@softure-ai/deploy 0.0.0). The app
# owns this file now; init never overwrites it without --force.
#
# The release ships docker/prod/hooks/ next to deploy.sh, and deploy.sh runs every hook of deploy.json in that folder
# (/srv/softure-example/), so a hook script starts with:
#
#   set -euo pipefail
#   . hooks/lib.sh
#
# and is listed as { "name": "<hook>", "run": ["bash", "hooks/<hook>.sh"] }.

# Prints "hook: <message>" on stderr and exits 1, which fails the hook's step.
fail() {
  printf 'hook: %s\n' "$*" >&2
  exit 1
}

# docker compose with the live release's compose file and .env.prod, as deploy.sh runs it.
compose() {
  docker compose --env-file .env.prod --file docker-compose.yml "$@"
}

# Prints the value of NAME in .env.prod, without the single quotes `softure-deploy env render` may put around it.
# Fails when NAME is not there; never prints a value in a message.
env_value() {
  local name="$1" line value
  if [[ ! "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then fail "env_value: $name is not a variable name."; fi
  line="$(grep "^$name=" .env.prod | tail -n 1)" || fail "$name is not in .env.prod."
  value="${line#*=}"
  if [ "${#value}" -ge 2 ] && [ "${value:0:1}" = "'" ] && [ "${value: -1}" = "'" ]; then
    value="${value:1:${#value}-2}"
  fi
  printf '%s\n' "$value"
}

# Fails unless NAME's value in .env.prod has at least MIN characters (a secret too short to be safe).
require_min_length() {
  local name="$1" min="$2" value
  if [[ ! "$min" =~ ^[1-9][0-9]*$ ]]; then fail "require_min_length: $min is not a positive length."; fi
  value="$(env_value "$name")" || exit 1
  if [ "${#value}" -lt "$min" ]; then fail "$name in .env.prod is shorter than $min characters."; fi
}
