// Copying one account between two databases: the rows the account owns (found through foreign
// keys, also in tables without a user column), exact values, a dry run by default, and refusals
// that write nothing.
import { copyAccount, recordConsent } from "@softure-ai/privacy/server";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createTestPrivacy, findTraces, seedUser, type SeededUser, type TestPrivacy } from "./support.js";

/**
 * App tables beyond the shared fixture: a review owned by its author (CASCADE) that names the admin
 * who checked it (SET NULL, a mention), a line table that only references the review, and a
 * table keyed by email with no foreign key at all.
 */
const EXTRA_TABLES = `
  CREATE TABLE public.reviews (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    checked_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
    checked_at timestamptz,
    amount numeric(12, 2)
  );
  CREATE TABLE public.review_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id uuid NOT NULL REFERENCES public.reviews (id) ON DELETE CASCADE,
    body text NOT NULL
  );
  CREATE TABLE public.line_notes (
    line_id bigint NOT NULL REFERENCES public.review_lines (id) ON DELETE CASCADE,
    body text NOT NULL
  );
  CREATE TABLE public.newsletter (
    email text PRIMARY KEY,
    subscribed_at timestamptz NOT NULL
  );
`;

const REVIEW_ID = "00000000-0000-4000-8000-000000000001";
const MICROSECONDS = "2026-09-01 10:20:30.421579+00";

async function createDatabase(): Promise<TestPrivacy> {
  const test = await createTestPrivacy();
  await test.database.client.exec(EXTRA_TABLES);
  return test;
}

async function readText(test: TestPrivacy, query: string, params: unknown[] = []): Promise<Record<string, unknown>[]> {
  await test.database.client.exec("SET TimeZone = 'UTC'");
  const result = await test.database.client.query<Record<string, unknown>>(query, params);
  return result.rows;
}

describe("copyAccount", () => {
  let source: TestPrivacy;
  let target: TestPrivacy;
  let ada: SeededUser;
  let bob: SeededUser;

  beforeEach(async () => {
    source = await createDatabase();
    target = await createDatabase();
    ada = await seedUser(source, "ada@example.com");
    bob = await seedUser(source, "bob@example.com");
    const client = source.database.client;
    await client.query("INSERT INTO public.reviews (id, user_id, checked_by, checked_at, amount) VALUES ($1, $2, $3, $4, NULL)", [
      REVIEW_ID,
      ada.id,
      bob.id,
      MICROSECONDS,
    ]);
    // Bob's own review: never copied with Ada.
    await client.query("INSERT INTO public.reviews (id, user_id, checked_at, amount) VALUES ($1, $2, NULL, 0)", ["00000000-0000-4000-8000-000000000002", bob.id]);
    await client.query("INSERT INTO public.review_lines (id, review_id, body) VALUES (41, $1, 'first'), (42, $1, 'second')", [REVIEW_ID]);
    await client.query("INSERT INTO public.line_notes (line_id, body) VALUES (42, 'a note on the second line')");
    await client.query("INSERT INTO public.newsletter (email, subscribed_at) VALUES ('ada@example.com', $1), ('bob@example.com', $1)", [MICROSECONDS]);
    // A consent Ada gave by email before she had an account, and one of a stranger.
    for (const email of ["Ada@Example.com", "eve@example.com"]) {
      const recorded = await recordConsent(source.ctx, { subject: { email }, purpose: "newsletter", granted: true, source: "waitlist" });
      if (!recorded.ok) throw new Error(`recordConsent failed with ${recorded.error}`);
    }
    // The target already holds a consent of its own, so a copied id would collide with it.
    await recordConsent(target.ctx, { subject: { email: "zoe@example.com" }, purpose: "newsletter", granted: true, source: "waitlist" });
  });
  afterEach(async () => {
    await source.database.close();
    await target.database.close();
  });

  it("dry-runs by default: writes nothing and reports every table the account reaches", async () => {
    const result = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, onMissingReference: "null" });

    expect(result).toEqual({
      ok: true,
      value: {
        committed: false,
        userId: ada.id,
        tables: [
          { table: "auth.users", rows: 1, nulledReferences: 0 },
          { table: "auth.password_resets", rows: 1, nulledReferences: 0 },
          { table: "auth.sessions", rows: 1, nulledReferences: 0 },
          { table: "auth.user_roles", rows: 1, nulledReferences: 0 },
          { table: "notes.notes", rows: 1, nulledReferences: 0 },
          { table: "privacy.consents", rows: 3, nulledReferences: 0 },
          { table: "public.profiles", rows: 1, nulledReferences: 0 },
          { table: "public.reviews", rows: 1, nulledReferences: 1 },
          { table: "public.review_lines", rows: 2, nulledReferences: 0 },
          { table: "public.line_notes", rows: 1, nulledReferences: 0 },
        ],
      },
    });
    expect(await findTraces(target.database, [ada.id, ada.email])).toEqual([]);
  });

  it("with commit, copies every owned row with exact times and NULLs, and nothing of anyone else", async () => {
    // Bob first, so the admin Ada's review names exists in the target.
    expect((await copyAccount({ from: source.database.db, to: target.database.db, userId: bob.id, commit: true })).ok).toBe(true);
    const result = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, commit: true });

    expect(result.ok && result.value.committed).toBe(true);
    const reviews = await readText(target, "SELECT checked_by::text, checked_at::text, amount FROM public.reviews WHERE user_id = $1", [ada.id]);
    expect(reviews).toEqual([{ checked_by: bob.id, checked_at: MICROSECONDS, amount: null }]);
    const lines = await readText(target, "SELECT l.id::int AS id, l.body, n.body AS note FROM public.review_lines l LEFT JOIN public.line_notes n ON n.line_id = l.id ORDER BY l.id");
    expect(lines).toEqual([
      { id: 41, body: "first", note: null },
      { id: 42, body: "second", note: "a note on the second line" },
    ]);
    const userQuery = "SELECT u::text AS row FROM auth.users u WHERE id = $1";
    expect(await readText(target, userQuery, [ada.id])).toEqual(await readText(source, userQuery, [ada.id]));
    const consents = await readText(target, "SELECT user_id::text AS user_id, email_key IS NOT NULL AS by_email FROM privacy.consents WHERE user_id = $1 OR email_key IS NOT NULL ORDER BY id", [ada.id]);
    // Zoe's own consent, then Ada's two registration consents and her email consent.
    expect(consents).toEqual([
      { user_id: null, by_email: true },
      { user_id: ada.id, by_email: false },
      { user_id: ada.id, by_email: false },
      { user_id: null, by_email: true },
    ]);
    expect(await readText(target, "SELECT count(*)::int AS count FROM public.newsletter")).toEqual([{ count: 0 }]);
  });

  it("gives copied rows with an unreferenced generated key a new key, and moves a written key's sequence past it", async () => {
    await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, commit: true, onMissingReference: "null" });

    // The target's own consent keeps id 1; Ada's three follow in their source order.
    const consents = await readText(target, "SELECT id::int AS id, user_id IS NULL AS by_email, source FROM privacy.consents ORDER BY id");
    expect(consents.map((row) => row.id)).toEqual([1, 2, 3, 4]);
    // review_lines.id is referenced by line_notes, so it is written as is, and the next line gets 43.
    const next = await readText(target, `INSERT INTO public.review_lines (review_id, body) VALUES ('${REVIEW_ID}', 'third') RETURNING id::int AS id`);
    expect(next).toEqual([{ id: 43 }]);
  });

  it("refuses a mention of a row the target lacks, unless asked to write it as NULL", async () => {
    const refused = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, commit: true });
    expect(refused).toMatchObject({ ok: false, error: "privacy.copy_reference_missing" });
    expect(!refused.ok && refused.detail).toContain("public.reviews");
    expect(await findTraces(target.database, [ada.id])).toEqual([]);

    const nulled = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, commit: true, onMissingReference: "null" });
    expect(nulled.ok).toBe(true);
    expect(await readText(target, "SELECT checked_by FROM public.reviews")).toEqual([{ checked_by: null }]);
  });

  it("refuses an unknown account and an account the target already has, writing nothing", async () => {
    expect(await copyAccount({ from: source.database.db, to: target.database.db, userId: "00000000-0000-4000-8000-00000000dead" })).toMatchObject({
      ok: false,
      error: "privacy.copy_account_missing",
    });
    expect(await copyAccount({ from: source.database.db, to: target.database.db, userId: "not-a-uuid" })).toMatchObject({
      ok: false,
      error: "privacy.copy_account_missing",
    });

    await seedUser(target, "ada@example.com");
    const existing = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, onMissingReference: "null" });
    expect(existing).toMatchObject({ ok: false, error: "privacy.copy_account_exists" });
    expect(!existing.ok && existing.detail).toContain("ada@example.com");
  });

  it("refuses a target table that lacks a column or types it differently", async () => {
    await target.database.client.exec("ALTER TABLE public.reviews DROP COLUMN amount");
    const missing = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, onMissingReference: "null" });
    expect(missing).toMatchObject({ ok: false, error: "privacy.copy_schema_mismatch" });
    expect(!missing.ok && missing.detail).toContain("public.reviews.amount");

    await target.database.client.exec("ALTER TABLE public.reviews ADD COLUMN amount numeric(14, 2)");
    const retyped = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, onMissingReference: "null" });
    expect(retyped).toMatchObject({ ok: false, error: "privacy.copy_schema_mismatch" });
    expect(!retyped.ok && retyped.detail).toContain("numeric(12,2)");
  });

  it("refuses a row the target's constraints reject, naming the constraint, and writes nothing", async () => {
    await seedUser(target, "zed@example.com");
    // The target holds a review with the same key under another account.
    const [zed] = await readText(target, "SELECT id::text AS id FROM auth.users WHERE email = 'zed@example.com'");
    await target.database.client.query("INSERT INTO public.reviews (id, user_id) VALUES ($1, $2)", [REVIEW_ID, zed?.id]);

    const result = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, commit: true, onMissingReference: "null" });
    expect(result).toMatchObject({ ok: false, error: "privacy.copy_conflict" });
    expect(!result.ok && result.detail).toContain("reviews_pkey");
    expect(await findTraces(target.database, [ada.id])).toEqual([]);
  });

  it("leaves out an excluded table and what only it reaches, and adds an included table by email", async () => {
    const result = await copyAccount({
      from: source.database.db,
      to: target.database.db,
      userId: ada.id,
      commit: true,
      onMissingReference: "null",
      exclude: ["auth.sessions", "public.review_lines"],
      include: [{ table: "public.newsletter", column: "email", matches: "email" }],
    });

    expect(result.ok && result.value.tables.map((entry) => entry.table)).toEqual([
      "auth.users",
      "auth.password_resets",
      "auth.user_roles",
      "notes.notes",
      "privacy.consents",
      "public.newsletter",
      "public.profiles",
      "public.reviews",
    ]);
    expect(await readText(target, "SELECT count(*)::int AS count FROM auth.sessions")).toEqual([{ count: 0 }]);
    expect(await readText(target, "SELECT email, subscribed_at::text FROM public.newsletter")).toEqual([{ email: "ada@example.com", subscribed_at: MICROSECONDS }]);
  });

  it("refuses an exclude or include naming a table the source does not have", async () => {
    const result = await copyAccount({ from: source.database.db, to: target.database.db, userId: ada.id, exclude: ["public.nothing"] });
    expect(result).toMatchObject({ ok: false, error: "privacy.copy_schema_mismatch" });
    expect(!result.ok && result.detail).toContain("public.nothing");
  });
});
