// `softure-blog skill install`: writes the skill into the app, overwrites only its own folder,
// `--check` for CI, and no database.
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_SKILL_DIR, runBlogCli, SKILL_MARKER, type CliOutput } from "@softure-ai/blog/cli";
import type { BlogOptionsInput } from "@softure-ai/blog";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createConfig } from "./support.js";

let app: string;
beforeEach(() => {
  app = mkdtempSync(join(tmpdir(), "blog-skill-"));
});
afterEach(() => {
  rmSync(app, { recursive: true, force: true });
});

async function runSkill(argv: readonly string[], options: BlogOptionsInput = {}) {
  const lines: string[] = [];
  const errors: string[] = [];
  const output: CliOutput = { log: (line) => lines.push(line), error: (line) => errors.push(line) };
  const code = await runBlogCli({
    config: createConfig(options),
    argv: ["skill", ...argv],
    cwd: app,
    output,
    openDatabase: () => Promise.reject(new Error("skill install must not open the database")),
  });
  return { code, lines, errors };
}

const SKILL_FILES = ["SKILL.md", "references/reviewer.md", "references/rules.md", "references/structure.md", "references/template.md"];

describe("softure-blog skill install", () => {
  it("writes the skill into .claude/skills/blog-write", async () => {
    const run = await runSkill(["install"]);
    expect(run.code).toBe(0);
    expect(run.errors).toEqual([]);
    for (const path of SKILL_FILES) expect(existsSync(join(app, DEFAULT_SKILL_DIR, path)), path).toBe(true);
    expect(run.lines.at(-1)).toBe("skill: installed into .claude/skills/blog-write; commit it, and run skill install --check in CI");
  });

  it("writes into --dir with the --command the app runs", async () => {
    const run = await runSkill(["install", "--dir", "agents/blog", "--command", "npm run blog --"]);
    expect(run.code).toBe(0);
    expect(readFileSync(join(app, "agents/blog/SKILL.md"), "utf8")).toContain("`npm run blog -- check content/blog/<slug>.md`");
  });

  it("overwrites a skill it generated before", async () => {
    await runSkill(["install"]);
    const run = await runSkill(["install"], { quality: { language: "pl" } });
    expect(run.code).toBe(0);
    expect(readFileSync(join(app, DEFAULT_SKILL_DIR, "SKILL.md"), "utf8")).toContain("Write in **Polish**.");
  });

  it("refuses a folder whose SKILL.md it did not generate, and leaves it alone", async () => {
    mkdirSync(join(app, DEFAULT_SKILL_DIR), { recursive: true });
    writeFileSync(join(app, DEFAULT_SKILL_DIR, "SKILL.md"), "# Our own skill\n");
    const run = await runSkill(["install"]);
    expect(run.code).toBe(1);
    expect(run.errors).toEqual(["softure-blog skill install: .claude/skills/blog-write/SKILL.md was not generated by this command; refusing to overwrite it (choose another --dir)"]);
    expect(readFileSync(join(app, DEFAULT_SKILL_DIR, "SKILL.md"), "utf8")).toBe("# Our own skill\n");
    expect(existsSync(join(app, DEFAULT_SKILL_DIR, "references"))).toBe(false);
  });

  it("--check is green after an install with the same config", async () => {
    await runSkill(["install"]);
    const run = await runSkill(["install", "--check"]);
    expect(run).toEqual({ code: 0, lines: ["skill: .claude/skills/blog-write is up to date"], errors: [] });
  });

  it("--check is red after a config change, names the files and writes nothing", async () => {
    await runSkill(["install"]);
    const before = readFileSync(join(app, DEFAULT_SKILL_DIR, "references/rules.md"), "utf8");
    const run = await runSkill(["install", "--check"], { quality: { severity: { exclamation: "error" } } });
    expect(run.code).toBe(1);
    expect(run.errors).toEqual([
      "skill: .claude/skills/blog-write/references/rules.md differs from the blog config",
      "skill: run softure-blog skill install with the same options and commit the folder",
    ]);
    expect(readFileSync(join(app, DEFAULT_SKILL_DIR, "references/rules.md"), "utf8")).toBe(before);
  });

  it("--check is red when the skill was never installed", async () => {
    const run = await runSkill(["install", "--check"]);
    expect(run.code).toBe(1);
    expect(run.errors).toHaveLength(SKILL_FILES.length + 1);
    expect(existsSync(join(app, DEFAULT_SKILL_DIR))).toBe(false);
  });

  it("refuses an app whose quality gate is off", async () => {
    const run = await runSkill(["install"], { quality: false });
    expect(run.code).toBe(1);
    expect(run.errors).toEqual(["softure-blog skill install: the quality gate is off (blog({ quality: false })); the writing skill is built on it"]);
  });

  it.each([
    [[], "skill needs a subcommand: install"],
    [["remove"], 'unknown skill subcommand "remove"; use install'],
    [["install", "somewhere"], 'skill install takes no paths; use --dir <path>, not "somewhere"'],
    [["install", "--command", " "], '--command needs the command, e.g. "npm run blog --"'],
  ])("exits 2 with the usage for %j", async (argv, problem) => {
    const run = await runSkill(argv);
    expect(run.code).toBe(2);
    expect(run.errors[0]).toBe(`softure-blog: ${problem}`);
  });

  it("marks the generated SKILL.md", async () => {
    await runSkill(["install"]);
    expect(readFileSync(join(app, DEFAULT_SKILL_DIR, "SKILL.md"), "utf8")).toContain(SKILL_MARKER);
  });
});
